//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValheimProject.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> id_biome { get; set; }
        public string description { get; set; }
        public Nullable<bool> is_delete { get; set; }
    
        public virtual Biome Biome { get; set; }
    }
}
